# --- Better defaults ---
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
#set -g renumber-windows on
set -sg escape-time 0
set -g history-limit 100000
set-option -g prefix C-b
set-option -sa terminal-overrides ",xterm*:Tc"

# --- Use vi keys in copy mode and command prompt ---
setw -g mode-keys vi
set -g status-keys vi

# --- Vim-like pane navigation ---
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# --- Resize panes with Vim keys ---
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# --- Windows = tabs ---
bind r command-prompt "rename-window %%"

# Vim-ish tab switching
bind -r C-h previous-window
bind -r C-l next-window

# --- Copy mode like Vim ---
bind Enter copy-mode

# In copy mode:
# v = begin selection
# y = yank selection
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# open new panes in current directory 
bind '%' split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Modern macOS clipboard integration
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.config/scripts/tmux-sessionizer/tmux-sessionizer"
bind-key -r M-h run-shell "tmux neww tmux-sessionizer -s 0"
bind-key -r M-t run-shell "tmux neww tmux-sessionizer -s 1"
bind-key -r M-n run-shell "tmux neww tmux-sessionizer -s 2"
bind-key -r M-s run-shell "tmux neww tmux-sessionizer -s 3"

# --- macOS clipboard integration ---
# Requires: brew install reattach-to-user-namespace
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
# bind-key y run-shell "tmux save-buffer - | reattach-to-user-namespace pbcopy"

# --- Reload config ---
bind R source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded";

# --- Status bar / tab bar ---
set -g status-position bottom
set -g status-right "bomdia"
set -g status-interval 5
#Status bar color
set -g status-bg color23
set -g status-fg color234

#setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #[bold]#I:#W#[default]< "

#Theme
set-window-option -g window-status-current-style bold,fg=color15,bg=color17
set-window-option -g window-status-style fg=color234
set -g window-status-activity-style bold,bg=color24,fg=color234
set-option -g message-style bg=color237,fg=colour231
set-option -g pane-border-style fg=color36
set-option -g pane-active-border-style fg=color35

# Change background color of a tab when activity occurs
setw -g monitor-activity on
# Do NOT reset the color of the tab after activity stops occuring
#setw -g monitor-silence 0
# Disable bell
setw -g monitor-bell off
# Disable visual text box when activity occurs
set -g visual-activity off

# --- Start names automatically from current process ---
setw -g automatic-rename on


